# Generated by Django 6.0 on 2026-01-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration_minutes', models.IntegerField()),
                ('language', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('genre', models.CharField(max_length=100)),
                ('poster_image', models.URLField(blank=True, max_length=500, null=True)),
                ('trailer_url', models.URLField(blank=True, max_length=500, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
            ],
        ),
    ]
